GET http://127.0.0.1:3000/cliente-proveedor?buscar=SRL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlhQG1haWwuY29tIiwiaWQiOiIzYjY3ODYwZS0wYzUxLTQ5MWMtYmY0OS00MWM0OWRkNjFhZjYiLCJpYXQiOjE3Njc4MzU3ODMsImV4cCI6MTc2NzgzOTM4M30.-siZhGe0DhNE79KVOxFP5bO9unkfdaAEZhSdID7kvB0
