POST http://127.0.0.1:3000/users
Content-Type: application/json

{
    "username": "carlos",
    "email": "carlos@mail.com",
    "password": "carlos54321",
    "role_ids": [1, 3]
}

### Listado de usuarios con paginación

GET http://127.0.0.1:3000/users?page=1&limit=2&search=

### mostrar un usuario

GET http://127.0.0.1:3000/users/6cc5bfbf-35bc-49bd-8efb-4429ed647fa7

### modificar
PATCH http://127.0.0.1:3000/users/2ac1ba18-90f5-4843-83ed-7dc918b040b8
Content-Type: application/json

{
  "username": "juan modificado",
  "email": "juan.modificado@mail.com",
  "password": "juanMODIFICADO54321",
  "isActive": true
}

### Eliminar Usuario
DELETE http://127.0.0.1:3000/users/39b0605a-3bf4-4d33-a84b-3bed14f7b336